# action.yml
name: 'Create PR'
description: 'Creates a PR'
inputs:
  branch_prefix:
    description: 'Branch prefix'
    required: false
    default: ""
  base_branch:
    description: 'Base branch'
    required: false
    default: ""
  request_title:
    description: 'Request title'
    required: false
    default: ""
  request_body:
    description: 'Request body'
    required: false
    default: ""
  draft_pr:
    description: 'Draft PR'
    required: false
    default: "false"
  github_token:
    description: 'Github token'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    BRANCH_PREFIX: ${{ inputs.branch_prefix }}
    BASE_BRANCH: ${{ inputs.base_branch }}
    PULL_REQUEST_TITLE: ${{ inputs.request_title }}
    PULL_REQUEST_BODY: ${{ inputs.request_body }}
    PULL_REQUEST_DRAFT: ${{ inputs.draft_pr }}
